### ISSUE TITLE
Default response headers in Flutter

### ISSUE THREAD

**Issue by TomRHandcock** [Apadmi-Engineering/Mockzilla#151]
Currently the Flutter package does not define any default headers in a `MockzillaHttpResponse`, this means the `Content-type: application-json` header is required to be added manually. Given JSON is the schema used for the vast majority of REST APIs we should look to have the `Content-type` header set by default.

We should be able to do this using a default parameter annotation on the `MockzillaHttpResponse` freezed class.

**Comment by JordanllHarper** [comment]
Happy to pick this one up

**Comment by TomRHandcock** [comment]
Closing this issue as it has been released in `mockzilla` v0.1.1.
