### ISSUE TITLE
Fix Kotlin API reference

### ISSUE THREAD

**Issue by TomRHandcock** [Apadmi-Engineering/Mockzilla#164]
The CSS formatting appears to have broken for the Dokka generated API reference ([source](https://apadmi-engineering.github.io/Mockzilla/dokka/index.html)) which makes the page largely unusable. The root cause appears to be 404 errors when the browser attempts to request the CSS stylesheets.

**Comment by mattmapadmi** [comment]
I think it's the whole thing has gone, but somehow the 404 page gets generated.
![image](https://github.com/Apadmi-Engineering/Mockzilla/assets/40175381/5959af9f-25af-483d-b0fb-0b04d6c4aec0)

**Comment by mattmapadmi** [comment]
Dokka is saying there's no docs

![image](https://github.com/Apadmi-Engineering/Mockzilla/assets/40175381/a68c490b-041a-4839-9508-eeac9795c7d8)

Guessing we've updated Kotlin tooling at some point that has angered it.
