### ISSUE TITLE
Add 'clear' button to logs viewer

### ISSUE THREAD

**Issue by TomRHandcock** [Apadmi-Engineering/Mockzilla#234]
The logs viewer can become saturated with entries; especially since they are preserved between host application restarts.

It would be nice to have a 'clear all' button present that deletes all the current log entries.

**Comment by Skeletonxf** [comment]
I can pick this up

**Comment by TomRHandcock** [comment]
Cheers @Skeletonxf

**Comment by Skeletonxf** [comment]
Done in https://github.com/Apadmi-Engineering/Mockzilla/pull/239
