### ISSUE TITLE
Flutter iOS Support

### ISSUE THREAD

**Issue by TomRHandcock** [Apadmi-Engineering/Mockzilla#49]
Currently the Flutter plugin only supports apps targeting Android. In order to cover both major mobile platforms an iOS implementation of the plugin should be created that calls into SwiftMockzilla. Dart’s Swift interop via ffigen doesn’t appear to be ready yet so using Pigeon in a similar manner to the Android implementation is likely the best route at this time.

**Comment by TomRHandcock** [comment]
Thought I would post an update about current efforts on this...

At time of writing [Flutter does not support SPM](https://github.com/flutter/flutter/issues/33850) and it looks unlikely this will change anytime soon. I am not extremely well versed in iOS packages however I see two possible solutions: the first is to embed SwiftMockzilla in the flutter package using a XCFramework, the second would be to add make SwiftMockzilla available in Cocoapods.

Think the latter option was preferred by @chedabob, @SamCosta1 Do you have a preference here?

**Comment by mattmapadmi** [comment]
Pods support RFC raised https://github.com/Apadmi-Engineering/Mockzilla/issues/54

**Comment by TomRHandcock** [comment]
While the library can now be used on iOS devices, I would still like to add unit tests for the `mockzilla_ios` bridging code as has been done in the `mockzilla_android` package. This was excluded from PR #91 with the reasoning that we would be able to gain more from trailing using the package on the fresh project than this unit testing.

**Comment by TomRHandcock** [comment]
Unit tests have been added in the above PR and are run as part of CI checks on PR builds. Closing this issue.
