### ISSUE TITLE
Align Dart-facing interface

### ISSUE THREAD

**Issue by TomRHandcock** [Apadmi-Engineering/Mockzilla#53]
As the current emphasis on the Flutter plugin is to 'make it work' on Android and iOS, the Dart-side interface is very minimal, this ticket it to improve it to a quality that is appropriate for dependants of Mockzilla.

Ideally the Dart-side interface should be consistent with the interface of the [KMP package](https://apadmi-engineering.github.io/Mockzilla/endpoints/) to improve maintainability and make writing documentation easier. To that end, the interface should include builders for the `MockzillaConfig` and `EndpointConfig` classes.

**Comment by JordanllHarper** [comment]
Happy to have a look at this

**Comment by JordanllHarper** [comment]
Should we close this issue now the interface has been merged or are there more improvements that can be made here?

**Comment by TomRHandcock** [comment]
Closing this issue as it was implemented in [PR #65](https://github.com/Apadmi-Engineering/Mockzilla/pull/65)
