### ISSUE TITLE
[RFC] Cocoapods support

### ISSUE THREAD

**Issue by mattmapadmi** [Apadmi-Engineering/Mockzilla#54]
# RFC Template

**Feature Name:** Add Cocoapods support to SwiftMockzilla

**Type:** Feature

**Start Date:** 2024-04-23

**Author:** Matt

**Related components:** SwiftMockzilla

## Summary

Add Cocoapods support to SwiftMockzilla alongside SPM. 

## Motivation

More flexibility for devs that aren't using SPM, and to support the Flutter package.

## Detailed design

N/A

## Drawbacks

Cocoapods isn't cool

## Alternatives

N/A

## Unresolved questions

None

**Comment by TomRHandcock** [comment]
Would be happy to look into this (since I am looking at a downstream issue) if there are no concerns about permissions.

**Comment by chedabob** [comment]
@TomRHandcock Ye go for it. I'll setup some credentials for pushing from Github.

**Comment by TomRHandcock** [comment]
Think this issue can now be closed. There is a release of 1.2.1 [now available on Cocoapods](https://cocoapods.org/pods/SwiftMockzilla) and automated releases have been setup in [PR#77](https://github.com/Apadmi-Engineering/Mockzilla/pull/77).
