### ISSUE TITLE
[Feature Request] Endpoint versioning

### ISSUE THREAD

**Issue by Skeletonxf** [Apadmi-Engineering/Mockzilla#59]
When an API is changed in a breaking way and users of mockzilla have cached mock data for that endpoint the cached data is not automatically cleared, leading to breakage and requiring the user to know that they need to clear all caches via the mockzilla UI

This can be worked around by versioning endpoints so that stale caches are not used after breaking changes, but comes with the downside of leaving orphaned caches around

```kotlin
EndpointConfiguration.Builder(id = /* endpoint name plus version number */).build().copy(name = /* endpoint name */)
```

Adding endpoint versioning to Mockzilla directly means it can actually clear the caches rather than orphan them.

**Comment by SamC-Apadmi** [comment]
Work is complete and merged, will be released as part of planned V2 release

**Comment by JordanllHarper** [comment]
Worth closing this issue?
