### ISSUE TITLE
Setup pub.dev publisher

### ISSUE THREAD

**Issue by TomRHandcock** [Apadmi-Engineering/Mockzilla#89]
Associating a package on pub.dev with a verified publisher gives the package more legitimacy as packages without this associated are shown as being uploaded by "unverified publisher". This task is to create a verified publisher for Mockzilla (possibly to be used by other Apadmi things in future).

Relatively straight-forward, there is only one high level requirement:

- Be created by the owner of a verified domain property from the Google search console

Upon creation, the owner's email address will be listed as the contact address for the publisher. This can (and arguably should) be changed to something multiple maintainers can access to avoid bottle-necks.

**Comment by mattmapadmi** [comment]
Tracking this internally here https://apadmi.atlassian.net/browse/IF-1

**Comment by TomRHandcock** [comment]
Published has been setup with a number of contributors added. Closing this issue.
